### PR TITLE
Add Previewify image provider

### PR DESCRIPTION
**Pull request by tpetry**
Additionally to the Flipp image provider, I integrated the Previewify image provider for social images.

### CODE REVIEW

**Comment by stancl** [comment]
Awesome PR! The implementation is perfect.

I'll wait for #22 (in case we find some issue in the `@seo` implementation) and then merge this.

**Comment by stancl** [comment]
Looks good to me. Let me know if this is ready to be merged.

**Comment by tpetry** [comment]
It's ready.

**Comment by stancl** [comment]
Thanks a lot!

**Pull request merged**
